---
- name:  elasticsearch set up playbook
  hosts: ansible_servers
  gather_facts: false
  tasks:
    - name: change account to elasticsearch
      shell: su elasticsearch
      when:  handleType == "start"

    - name: start
      shell: /usr/local/elasticsearch-cluster/elasticsearch-a/bin/elasticsearch -d
      when:  handleType == "start"

    - debug:
        msg: "start"
