---
- name: elasticsearch install
  hosts: ansible_servers
  gather_facts: false
  tasks:
    - name: install es
      shell: mkdir  /usr/local/elasticsearch-cluster && cd /tmp && tar zxvf elasticsearch-7.17.9-linux-x86_64.tar.gz  -C /usr/local/elasticsearch-cluster &&
      cd /usr/local/elasticsearch-cluster && mv elasticsearch-7.17.9 elasticsearch-a && mkdir -p /usr/local/elasticsearch-cluster/elasticsearch-a/data &&
      mkdir  -p /usr/local/elasticsearch-cluster/elasticsearch-a/logs
      register: installResult

    - debug:
        msg: "time update --> {{ installResult }}"
