---
- name: Time Update
  hosts: all
  gather_facts: false
  tasks:
    - name: install ntpdate
      shell: yum install -y ntpdate
      register: installResult

    - name: update date from ntp1.aliyun.com
      shell: ntpdate ntp1.aliyun.com
      register: ntpdateResult

    - debug:
        msg:
        - "time update --> {{ installResult }}"
        - "ntpdateResult --> {{ ntpdateResult }}"
